# WaveCLIP encoder configuration
clip_model: "ViT-B-14"   
K: 3                      
wavelet: "db1"            
use_ll: true              
D_clip: 512               
D_hidden: 512             
P: 14                     
D_sty: 1024               
P_sty: 8                  
